name: Smart Image Consolidator

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  image-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Set PR Environment Variables
        run: |
          echo "GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Check Docker & Buildx
        run: |
          docker --version
          docker buildx version

      - name: Install AnchoreCTL
        run: |
          curl -sSL https://github.com/anchore/anchore-cli/releases/download/v1.7.2/anchore-cli-linux-amd64 -o /usr/local/bin/anchore
          chmod +x /usr/local/bin/anchore
          anchore version

      - name: Install Go Dependencies
        run: go mod tidy

      - name: Build and Run Smart Image Consolidator
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          go build -o consolidator main.go
          ./consolidator
